apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
      - name: conversao
        image: maiconnf1980/conversao-temperatura:v1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
